{
  transerrors_source: 'C:\API\Requests\getTransErrors.txt',
  pagination_source: 'C:\API\Requests\pagination.txt',
  getAllErrorFieldsForGrp_source: 'C:\API\Requests\getAllErrorFieldsForGrp.txt',
  getTransErrorsCount_source: 'C:\API\Requests\getTransErrorsCount.txt',
  getFilteredTransErrors_source: 'C:\API\Requests\getFilteredTransErrors.txt',
  updateBulkCorrectWithFilterGrp_source: 'C:\API\Requests\updateBulkCorrectWithFilterGrp.txt',
  updateBulkIgnoreWithFilterGrp_source: 'C:\API\Requests\updateBulkIgnoreWithFilterGrp.txt',
  transerrors_destination: 'C:\API\Prod\Responses\getTransErrors_prod',
  pagination_destination: 'C:\API\Prod\Responses\pagination_prod',
  getAllErrorFieldsForGrp_destination: 'C:\API\Prod\Responses\getAllErrorFieldsForGrp_prod',
  getTransErrorsCount_destination: 'C:\API\Prod\Responses\getTransErrorsCount_prod',
  getFilteredTransErrors_destination: 'C:\API\Prod\Responses\getFilteredTransErrors_prod',
  updateBulkCorrectWithFilterGrp_destination: 'C:\API\Prod\Responses\updateBulkCorrectWithFilterGrp_prod',
  updateBulkIgnoreWithFilterGrp_destination: 'C:\API\Prod\Responses\updateBulkIgnoreWithFilterGrp_prod',
  transerrors_request: '{"include":[{"globalclientcd":["4420","3190"]}],"includeCriticalErrors":"1"}',
  getAllErrorFieldsForGrp_request: '{"include":[{"dataid":["IV"]}],"exclude":[],"includeCriticalErrors":"1","filter":[],"group":{"name":"globalclientcd","value":"0038"}}',
  getTransErrorsCount_request: '{"groups":[{"groupId":"admin2","include":[{"dataid": ["IC"]}],"exclude":[],"includeCriticalErrors": "1"}]}',
  pagination_request: '{"groupId":"eX_dataid_In_rest_0","include":[{"globalclientcd":["4420","3190"]}],"includeCriticalErrors":"0"}',
  getFilteredTransErrors_request: '{"include":[{"globalclientcd":["1003"]}],"exclude":[{"dataid":["IN"]}],"includeCriticalErrors":"1","filter":[{"column":"globalclientname","value":"MARSH & MCLELLAN COMPANIES (MMC)"}],"order":{"column":"errorDesc","value":"asc"},"combined":{"column":"errorType"}}'


}
